name: release-validation

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  assemble-release:
    runs-on: ubuntu-latest
    env:
      CI: "true"
      WIFIGUARD_RELEASE_STORE_FILE: app/keystore/release-key.jks
      WIFIGUARD_RELEASE_STORE_PASSWORD: ${{ secrets.WIFIGUARD_RELEASE_STORE_PASSWORD }}
      WIFIGUARD_RELEASE_KEY_PASSWORD: ${{ secrets.WIFIGUARD_RELEASE_KEY_PASSWORD }}
      WIFIGUARD_RELEASE_KEY_ALIAS: ${{ secrets.WIFIGUARD_RELEASE_KEY_ALIAS }}
      WIFIGUARD_RELEASE_KEYSTORE_B64: ${{ secrets.WIFIGUARD_RELEASE_KEYSTORE_B64 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Materialize keystore from secrets
        run: |
          mkdir -p app/keystore
          echo "${WIFIGUARD_RELEASE_KEYSTORE_B64}" | base64 --decode > app/keystore/release-key.jks
          chmod 600 app/keystore/release-key.jks

      - name: Validate signing inputs before build
        run: ./gradlew -p app :app:validateReleaseSigning

      - name: Assemble release build
        run: ./gradlew assembleRelease --no-daemon --stacktrace

